### PR TITLE
Add an abstraction layer to the API

### LINKED ISSUE #99: add an abstraction layer to the API
after we have a few pages making API calls - read on the prospects page, write on the add story page, update on the edit and approve page - we should refactor our usage of the API to remove the direct dependency on our specific dev API.

the general idea is to create a layer in-between the application code and the code actually calling the API. this would allow us to swap out API details/code without changing any application code.

if a planning phase would be helpful with this phase, please feel free to add ideas here for review before going to the code.

### PR DESCRIPTION
**Pull request by nina-py**
## Goal

Add wrappers to Apollo Client calls in frontend code so that a different API can be used down the track.

- First commit: queries done - mutations to follow.

Closes #99.

## Implementation Decisions

Installed `graphql-codegen` packages to generate types for both the local and the AWS AppSync schemas on the basis of the queries we actually use - so not the whole schema (see `src/api/local/generatedTypes.ts` and `src/api/aws-appsync/generatedTypes.ts`. 

Added thin wrappers to Apollo hooks that normalise data returned by both APIs - see `src/local/hooks` and `src/aws-appsync/hooks` - these will allow me to mock the metadata in the local API as well.

No longer wrapping the entire app in an `<ApolloProvider>` component - instead I'm passing the client directly with each query. This leaves the door open for future APIs to be REST APIs rather than GraphQL ones as the frontend code, for the most part, is no longer tied to a particular API implementation and a particular API client such as Apollo. 

The only constraint is that the future API should implement hooks for each query/request that return an object with { loading, error, data }. `Error` is still expected to be `ApolloError` by the `HandleApiResponse` component but I should be able to abstract that away as well. Tests still expect the shape of the data to be that of what AWS AppSync returns - will adjust that, too.

The app now defaults to using the local API - make sure you have generated some data and started up the local GraphQL server using the commands documented in the README file. To switch to the AWS API, add `REACT_APP_USE_POCKET_API=true` to environment variables. 

To do:

- [ ] Get mutations working with local API
- [x] Update tests
- [ ] Update any installation documentation
- [x] Review TODOs in the code and action those where the local API solves the problem (i.e. article counts).

### CODE REVIEW

**Comment by jpetto** [comment]
i just pulled this locally and got the prospects tab running with the local api! this is a really nice approach. 😄

**Comment by nina-py** [comment]
I have refactored AWS AppSync mutations to use the generatedTypes. The local API ones are yet to be done. Mutations are trickier to hide behind an abstraction layer - primarily because, unlike a call to a REST API, you can't use a mutation hook inside a statement - the mutation needs to be prepared in the body of the functional component and it returns a function that will actually execute the mutation and that function in turn *can* be used inside, say, a `handleSubmit` function. So a two-step process. 

Because of that - and the fact that some tests won't run if I call the Apollo client behind the scenes (the executed code will attempt to connect to the actual API instead of using a mock client provided by `MockedProvider`) - the app overall is back to being tightly coupled to a GraphQL API implementation. 

I think that if the future production API turns out to be a REST one, the local API will have to be updated to a REST one, too - this will be less work than trying to get two very different approaches working alongside each other. Apollo is fantastic with its caching and integrated state management, but it comes at a price - you can't easily swap it out for something else in the frontend code. 

For now, I am persevering with getting a GraphQL local API going - the queries are very easy to set up, mutations are more of a headache, and to get the Add Story working locally in particular I may have to add even more Apollo-specific code to the component in question.

**Comment by nina-py** [comment]
I've marked this ready for review with some caveats - the two local API mutations are still not complete! I have to pull the plug on them for the time being though and see if I can tackle them atomically over the coming days. With the mutations, I'm stuck in an endless loop of either the app or the tests failing - but never both failing or working at the same time! :) 

For now, I'd really like to focus on building out the rest of the queries for the Prospects and New Tab pages and assembling an overview of what other frontend work is still outstanding. Here is the final list of work completed in this PR, taken from the squashed commit:

- Added graphql-codegen packages to generate types and custom Apollo hooks for both local and remote APIs.

- Refactored all of the AppSync API to use the new generated types.

- Set up queries for the local API and a way to switch between the two APIs.

- Reorganised component and page imports throughout.

- Fixed bug with author field updates never making it to the backend on prospect approval.

**Review by kkyeboah — APPROVED** [review]
Looks like there's more to be done here but getting this in will unblock some of the required work on the frontend.

Approving and merging to unblock.

**Pull request merged**
