### PR TITLE
 created button and added hover to it too

### PR DESCRIPTION
**Pull request by qmya**
## Goal

Insert purpose of pull request

## Todos:
- [ ] Outstanding todo
- [x] Completed todo
 
## Implementation Decisions

### CODE REVIEW

**Comment by qmya** [comment]
Hey, @jpetto  and @kkyeboah I redid the changes in this pull request. Could you review the 2nd changes? Thanks 😃

**Review by kkyeboah — CHANGES_REQUESTED** [review]
This is a great start, and certainly one way to look at it if all the buttons were going to be used in a single component. However, this button component needs to be reusable and should render a single button. 

What do you think about making the variants of this button by having the component accept `props` for the variants?

Don't worry about matching the screenshot in the demo, it's fine for the buttons to be stacked on each other or not have any spacing at all.

**Comment by qmya** [comment]
Hey @kkyeboah, Thanks for the feedback. I am trying it right now :)

**Comment by qmya** [comment]
hey @kkyeboah , I should make separate components for each button and then render in App.js, and also the buttons will receive the props from App.js.  Am I right?

**Comment by kkyeboah** [comment]
@qmya This should be a single component that can be rendered differently based on the props passed to it. To your question, the buttons, in this case, will have props in `App.tsx`.

The point here is that the `<Button>` component shouldn't have all the buttons rendered within it as it is now. Another component should be able to use the `<Button>` component, render a single button, for example, and change the look (grey, red, or green) by simply passing the appropriate props. I hope this helps.

**Comment by qmya** [comment]
Yes, it is helpful, I am just trying to understand :)

**Comment by kkyeboah** [comment]
> @qmya This should be a single component that can be rendered differently based on the props passed to it. To your question, the buttons, in this case, will have props in `App.tsx`.
> 
> The point here is that the `<Button>` component shouldn't have all the buttons rendered within it as it is now. Another component should be able to use the `<Button>` component, render a single button, for example, and change the look (grey, red, or green) by simply passing the appropriate props. I hope this helps.

For  example in `App.tsx` there should be 4 components:
`<Button text="Button 1" size="small" type="positive"/>`
`<Button text="Button 2" size="medium" type="negative"/>`
`<Button text="Button 3" size="large" type="neutral"/>`
`<Button text="Button 4" size="small" type="hollow"/>`

The `<Button/>` component should render all these different to match the comp attached to the issue. See below
Screen Shot 2020-10-26 at 12 14 32 PM

**Comment by qmya** [comment]
Hi, @kkyeboah Thanks for your explanation on my PR. I am so sorry that I took the time your time in reviewing my PR. Believe me, this time it's all good 💃 

I really appreciate your feedback and time also ❤️

**Review by kkyeboah — CHANGES_REQUESTED** [review]
This is definitely a much better implementation. Your buttons, however, are missing the following:
- The material ui feel - by this I mean the box-shadows on the buttons.
- The hover states make the buttons invisible on a white background. Try lightening the color by a small percentage on hover

You could figure out how to customize the color of the the default material ui buttons and that should get you most of the way there. This link should be helpful: https://material-ui.com/components/buttons/
You may also find this link help for customizing the material ui button component: https://material-ui.com/customization/components/

**Comment by qmya** [comment]
Hey @kkyeboah I try this time to use the material UI button from the link you shared and I am sure this time the UI will look good :)

**Comment by qmya** [comment]
Hey, @kkyeboah I removed the border on hover and also resolved conflicts in the package.json. I hope everything will be okay now 😄  Thanks for your time.

**Comment by qmya** [comment]
Hey, @kkyeboah I revert the changes in App.tsx to its original. Could you review it and approve it thanks a lot :)

**Comment by alicendeh** [comment]
Hi @qmya  do you still need help?

**Comment by alicendeh** [comment]
If your still facing difficulties reverting then you can follow the steps below
Save your files (Modification you made) > Delete your local copy > close all pull requests you made > Delete your github fork > Fork back > Clone back > add you changes (Files you saved iin step 1) > Add > commit > push > Create a pull request

**Pull request merged**
