### PR TITLE
Add correct buttons and labels to prospect cards

### PR DESCRIPTION
**Pull request by nina-py**
## Goal

Update Prospects tabs so that each view shows customized cards with the correct buttons and labels.

- Each Prospects tab now shows the appropriate buttons (these are not yet wired to anything).

- All tabs except the default ("Pending") tab show prospects with labels ("Rejected", "Approved", etc.) as noted in the "Frontend Questions" document.

- Card component has been reworked to be mobile-friendly and match Figma comps.
 
## Implementation Decisions

As noted in the "Frontend Questions" document, I have dropped the "Edit & Approve" button from the "Rejected" tab. 

Labels are green (primary color) for Approved/Live/Scheduled prospects, brick red for Rejected prospects and default grey for Snoozed prospects.

In desktop view, thumbnail images now take up ~33% of the available width rather than 30% they used to be - instead of custom styles, I'm using MUI grids and this also seems a closer match for Figma comps.

Also, I took out the unnecessary URLs out of the buttons that should just perform a mutation without redirecting the user anywhere - this solves the flicker of a URL change noted by @kkyeboah in a recent review.

### CODE REVIEW

**Review by kkyeboah — COMMENTED** [review]
@nina-py I couldn't get this to render locally. 
Steps to reproduce:
- npm install
- npm run api:generate-data
- npm run api:start

In another terminal tab/window:
- npm run start

Expectation:
The app renders in the browser.

Actual:
The app renders a blank page in the browser

Is there something else I should be doing to get this running locally to test?

**Comment by nina-py** [comment]
I had this issue earlier this week. I even set up a separate checkout and
that second checkout also didn't work. Only in my case I couldn't get the
'main' branch going after you merged one of my PRs.

I thought this might be a browser caching issue but it didn't work in
Chrome either. I suspect it was an issue with the local GraphQL server, but
it wasn't fixed with restarting the API server, the only thing that fixed
it for me was a complete reboot of my laptop.

>

**Review by kkyeboah — APPROVED** [review]
I managed to run this locally, I think it was the `db.json`. Removing and going through the steps I outlined in my previous comment got the app to render in the browser.

The cards look good! Nice work

**Comment by kkyeboah** [comment]
We should update the readme instructions when we get the chance on how to get started with the repo as it is.

**Comment by nina-py** [comment]
@kkyeboah, thank you for pointing this out - some of the script names have changed since I last edited the README file. Addressed in #124.

**Pull request merged**
