### PR TITLE
Update setup documentation

### PR DESCRIPTION
**Pull request by nina-py**
## Goal

Keep the docs updated as the code evolves.

## Implementation Decisions

- Updated script name to run to generate data for the local API and path to generated db.json file.

- Reworded the section on starting up the local GraphQL server to make it clear that the main point of entry is the app, not the GraphiQL editor used for running test queries or debugging them.

- Added a section on updating generated types and helper functions for the local API.

### CODE REVIEW

**Review by jpetto — CHANGES_REQUESTED** [review]
love the docs update!

only requesting changes as currently i get a blank white screen when running locally. i haven't run the site locally in some time so i don't know if the recent merge of #123 is relevant here or not. maybe i have a missing/extra local config?

this is all i see in my console:

Screen Shot 2021-02-16 at 9 58 57 AM

the graphql server is up and running and works (verified in GraphiQL interface).

any ideas? (blocking this PR as maybe this discussion will result in additions to these docs.)

**Comment by nina-py** [comment]
@jpetto, good point. What causes this is still only a theory, but all three of us have had this issue by now and it needs to be included in the docs.

**Comment by nina-py** [comment]
@jpetto FYI - previous discussion of the blank screen issue: https://github.com/Pocket/curation-tools-frontend/pull/122#issuecomment-776939657. For me, only the reboot fixed everything, but Kelvin managed to get it working without a reboot.

**Comment by nina-py** [comment]
Hi @jpetto, I've updated the docs - after some experimentation, I found this happens when, after an update to the schema or queries, you restart the local GraphQL server and the frontend up. Both need to be powered down and started up again, and if the structure of the data has been updated, a fresh run of the `api:generate-data` script is also needed. 

Please let me know if my instructions for fixing this are clear enough - if not I'll expand them into a step-by-step process so that anyone new to this repo doesn't have to look up the commands elsewhere on the page.

**Comment by nina-py** [comment]
Hi @jpetto, just noticed that this PR is still outstanding, perhaps because the status says "Changes requested"? I can't see anywhere where I can respond to this request for changes so that the reviewer gets notified so I'm hoping you see this message instead! :)

**Review by jpetto — APPROVED** [review]

**Pull request merged**
